# 2.5 — Score a checkpoint on the manually-labeled honest set

Fast alternative to running the full labeling pass in `3-...ipynb` just to read the
honest accuracy at the bottom. This predicts **only** the ~150 hand-labeled `unknown`
events and runs the same comparison, so you can sweep checkpoints (e.g. each
`attempt4-...-epoch-N`) in seconds instead of ~23 min.

Point `model_dir` at a checkpoint and Run All.

## Setup

In [1]:
import os
import pandas as pd
import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer
import plotly.express as px

/home/martan/Nienke/Protest_Labelling/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
DATA_DIR = '../data'
MODELS_DIR = '../models'

# Point this at any checkpoint to score it on the honest manual set.
model_dir = f'{MODELS_DIR}/attempt7-t5-leave-keywords-in-epoch-2/hf_transformer_model'

MANUAL_DIR = f'{DATA_DIR}/manual_labelled_data'
INPUT_CSV  = f'{DATA_DIR}/labeled.csv'                # source of clean_notes for the manual events
TRAIN_CSV  = f'{DATA_DIR}/labeled_balanced_20.csv'   # only for label fallback

## Acceptance table (lenient scoring)

Some classes are near-synonyms (`climate`/`environment`) or routinely interchangeable
for a human annotator. Alongside **strict** accuracy (exact match), score a **lenient**
accuracy where a prediction counts as correct if it shares an acceptance group with the
gold label. Edit `ACCEPTANCE_GROUPS` to tune what's considered interchangeable.

In [3]:
# --- Acceptance table -------------------------------------------------------
# Near-synonym classes that may be scored interchangeably. A prediction is
# "accepted" if pred matches any gold label (primary or a manual_label_alt) or
# shares a group below with one. Groups may overlap; acceptance checks shared
# membership only, so it never chains (blm<->discrimination and
# blm<->unjust law enforcement both pass, but discrimination<->unjust law
# enforcement does not). Comment a line out to tighten.
ACCEPTANCE_GROUPS = [
    {'climate', 'environment'},                                  # ecology / green
    {'discrimination', 'women rights', 'lgbtq', 'blm'},          # equality & identity
    {'unjust law enforcement', 'blm'},                           # policing / state violence
    {'immigration', 'discrimination'},                           # anti-migrant racism
    {'farmers', 'labor rights'},                                 # agrarian livelihoods
    {'public services', 'health care', 'education', 'housing'},  # public-sector provision
]

def gold_labels(row):
    """All hand-assigned valid labels for an event: primary + any '|'-joined alts."""
    g = {row['manual_label']}
    alt = row.get('manual_label_alt')
    if isinstance(alt, str) and alt.strip():
        g |= {x.strip() for x in alt.split('|') if x.strip()}
    return g

def accepts(golds, pred):
    """True if pred matches any gold label or shares an acceptance group with one."""
    return any(g == pred or any(g in s and pred in s for s in ACCEPTANCE_GROUPS) for g in golds)

## Load the checkpoint

In [4]:
print(f"--- Loading {model_dir} ---")
loaded_tokenizer = AutoTokenizer.from_pretrained(model_dir)
loaded_model = AutoModelForSequenceClassification.from_pretrained(model_dir)

# CPU on purpose: only ~80 events, so it's a few seconds and skips the slow GPU
# kernel warm-up — and leaves the GPU free for a training run.
load_device = torch.device("cpu")
loaded_model.to(load_device).eval()
print(f"Using device: {load_device}")

--- Loading ../models/attempt7-t5-leave-keywords-in-epoch-2/hf_transformer_model ---

Loading weights: 100%|██████████| 261/261 [00:00<00:00, 10447.83it/s]

Using device: cpu

In [5]:
# Class names from the model config; fall back to the training CSV for old
# models saved with generic LABEL_0..N names (mirrors notebook 3).
id2label = {int(k): v for k, v in loaded_model.config.id2label.items()}
if all(str(v).startswith("LABEL_") for v in id2label.values()):
    _t = pd.read_csv(TRAIN_CSV)
    _t = _t[~_t['class'].isin(['NoN', 'unknown'])]
    id2label = {i: name for i, name in enumerate(sorted(_t['class'].unique()))}
assert len(id2label) == loaded_model.config.num_labels

## Predict the manual events only

The manual CSVs carry `event_id_cnty` but not `clean_notes`, so pull the text from
`labeled.csv` by id, then run the model on just those rows.

In [6]:
ids = set(pd.read_csv(f'{MANUAL_DIR}/{'random_unknown_labeled.csv'}', usecols=['event_id_cnty'])['event_id_cnty'])

src = pd.read_csv(INPUT_CSV, usecols=['event_id_cnty', 'clean_notes'], low_memory=False)
eval_df = src[src['event_id_cnty'].isin(ids)].copy()
eval_df['clean_notes'] = eval_df['clean_notes'].fillna('').astype(str)
print(f"manual events: {len(ids)} | matched in labeled.csv: {len(eval_df)}")

texts = eval_df['clean_notes'].tolist()
preds, BATCH = [], 64
for i in range(0, len(texts), BATCH):
    batch = loaded_tokenizer(texts[i:i+BATCH], return_tensors='pt',
                             padding='longest', truncation=True, max_length=128)
    batch = {k: v.to(load_device) for k, v in batch.items()}
    with torch.inference_mode():
        logits = loaded_model(**batch).logits
    preds.extend(logits.argmax(dim=1).cpu().tolist())

eval_df['predicted_class'] = [id2label[p] for p in preds]
this_model = eval_df[['event_id_cnty', 'predicted_class']]

manual events: 200 | matched in labeled.csv: 200

## Honest comparison (same as the end of notebook 3)

In [7]:
def load_eval(path):
    d = pd.read_csv(path).drop(columns=['predicted_class_model'], errors='ignore')  # injected live below
    d = d.merge(this_model, on='event_id_cnty', how='left').rename(
        columns={'predicted_class': 'predicted_class_model'})
    d['model_correct'] = d['predicted_class_model'] == d['manual_label']
    d['students_correct'] = d['predicted_class_students'] == d['manual_label']
    # lenient: near-synonym classes + per-event multi-labels count as correct
    golds = d.apply(gold_labels, axis=1)
    d['model_accept'] = [accepts(g, p) for g, p in zip(golds, d['predicted_class_model'])]
    d['students_accept'] = [accepts(g, p) for g, p in zip(golds, d['predicted_class_students'])]
    d['agree'] = d['predicted_class_model'] == d['predicted_class_students']
    return d

rand = load_eval(f'{MANUAL_DIR}/random_unknown_labeled.csv')      # random unknown events (honest)
assert rand['predicted_class_model'].notna().all(), 'some events missing from labeled.csv'
print(f"random (honest): {len(rand)}")
print(f"strict  -> this model {rand['model_correct'].mean():.0%} | students {rand['students_correct'].mean():.0%}")
print(f"lenient -> this model {rand['model_accept'].mean():.0%} | students {rand['students_accept'].mean():.0%}")

random (honest): 200
strict  -> this model 55% | students 55%
lenient -> this model 66% | students 69%

In [8]:
n = len(rand)
ci = lambda p: 1.96 * (p * (1 - p) / n) ** 0.5  # normal-approx 95% CI (small n!)

head = pd.DataFrame([
    {'source': 'This model', 'scoring': 'strict',  'accuracy': rand['model_correct'].mean()},
    {'source': 'This model', 'scoring': 'lenient', 'accuracy': rand['model_accept'].mean()},
    {'source': 'Students',   'scoring': 'strict',  'accuracy': rand['students_correct'].mean()},
    {'source': 'Students',   'scoring': 'lenient', 'accuracy': rand['students_accept'].mean()},
])
head['ci'] = head['accuracy'].map(ci)
fig = px.bar(head, x='source', y='accuracy', color='scoring', barmode='group',
             text=head['accuracy'].round(3), error_y=head['ci'],
             labels={'source': '', 'accuracy': 'Accuracy on random unknown'},
             color_discrete_map={'strict': '#636EFA', 'lenient': '#00CC96'})
fig.update_layout(title={'text': f'Honest accuracy: strict vs lenient (n={n}, 95% CI)', 'x': 0.5},
                  plot_bgcolor='white', width=680, height=440, yaxis={'range': [0, 1]})
fig.show()

In [9]:
# Per-event labels: manual (truth) + any alt golds, our model, students, whether the
# model's label is accepted under ACCEPTANCE_GROUPS, and clean_notes (by event id).
cols = {'manual_label': 'manual', 'manual_label_alt': 'alt', 'predicted_class_model': 'our model',
        'predicted_class_students': 'students', 'model_accept': 'accepted', 'clean_notes': 'text'}

def table(df):
    return (df.merge(eval_df[['event_id_cnty', 'clean_notes']], on='event_id_cnty', how='left')
              [list(cols)].rename(columns=cols))


wrong = rand[~(rand['model_accept'] & rand['students_accept'])]   # at least one of them wrong
with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    print(f"At least one wrong (lenient): {len(wrong)}/{len(rand)}")
    display(table(wrong))

At least one wrong (lenient): 87/200

,manual,alt,our model,students,accepted,text
0,labor rights,NaN,public services,pandemic,False,striking stv journalist represented national union journalist nuj held picket outside scottish parliament edinburgh scotland row pay rise cost living crisis event part national day action
1,labor rights,NaN,climate,farmers,False,hundred unionized employee alro aluminium plant protested slatina complaining high price energy led reduction production capacity demanding permission company negotiate energy delivery directly energy producer
2,climate,NaN,public services,climate,False,extinction rebellion activist gathered outside stock exchange milano municipio 1 staged flash mob protest climate crisis demand finance tackle climate emergency
3,policies & politics,NaN,public services,housing,False,relative victim member mayor executive unrolled banner balcony town hall palazzo pretorio palermo palermo sicilia demand justice regarding death italian un aid worker found dead apartment san vincente del caguan colombia july 2020
4,climate,NaN,pandemic,environment,False,around 150 people mostly fff member cycled demonstrated halle saale call climate protection occasion co27 egypt cycled universitatsplatz passage 13 neustadt
5,environment,NaN,pandemic,environment,False,10 member rouvikonas threw flyer premise construction company northern athens protest construction landfill planned corfu
6,policies & politics,NaN,policies & politics,lgbtq,True,pegida staged protest dresden sachsen motto foot quergida fascism people staged counter protest several people held sit nearby protest motif specified
7,labor rights,NaN,labor rights,policies & politics,True,employee macedonian information agency protested skopje demanding salary national news agency increased parliament consider request
8,labor rights,farmers,climate,pandemic,False,striking fisher gathered port gallipoli lecce puglia protest increase oil gas price denounce impact category
9,labor rights,NaN,labor rights,public services,True,taxi driver representing app driver courier union gathered outside uber office manchester part 24 hour strike protest poor pay condition unfair dismissal driver demanded rate set 2 gbp per mile part series co ordinated strike member union across several city country attendance representative unite union
10,climate,NaN,pandemic,climate,False,friday future activist protested ravensburg climate action
11,immigration,NaN,policies & politics,policies & politics,False,several thousand people protested vienna inner city wien karlsplatz reception refugee right refugee protest organized platform human right attended amongst others granny right
12,public services,NaN,policies & politics,environment,False,resident village glogovo protested teteven claim unacceptable water rationing measure 25 year water supplied one hour per day demand local authority lovech something change
13,policies & politics,unjust law enforcement,unjust law enforcement,labor rights,True,2023 reported 40 anarchist gathered outside ministry health rome city center rom lazio protest detention well known anarchist activist article 41 bi prison regime started hunger strike 20 october 2022
14,policies & politics,NaN,policies & politics,pandemic,True,call reporter without border citizen demonstrated toulouse call liberation french journalist held hostage armed group mali
15,farmers,NaN,animal welfare,animal welfare,False,20 pig owner continued blockade yambol sliven road protest government decision slaughter pig due swine fever epidemic
16,environment,NaN,policies & politics,environment,False,50 activist resident protested diklo waste disposal site neighborhood
17,labor rights,NaN,public services,labor rights,False,repsol refinery worker held protest coruna galicia death worker unai martinez died accident refinery facility working
18,labor rights,NaN,public services,public services,False,around 100 sam foundry worker affiliated cgt union blocked train station rodez denounce closure factory
19,environment,NaN,policies & politics,policies & politics,False,100 150 people cgt affiliate municipal councilor enora chopard eelv gathered rouen normandie protest lack government action lubrizol factory fire 26 september 2019
20,policies & politics,NaN,policies & politics,public services,True,resident pakrovace near cacak protested delayed payment land seized construction highway area claimed price offered land low
21,unjust law enforcement,NaN,lgbtq,labor rights,False,around 100 people demonstrated front tribunal meaux denounce death year prisoner hand prison guard call justice
22,culture,NaN,ukraine-russia war,culture,False,croatian capital zagreb 200 people protested announced closure europe cinema oldest active cinema croatia
23,labor rights,NaN,public services,climate,False,fisher staged demonstration port bisceglie barletta andria trani puglia protest increase price diesel fuel
24,labor rights,NaN,discrimination,discrimination,False,30 social assistant protested targu mures included government ordinance 19 2024 affect remuneration argue exclusion discriminatory compared similar category included ordinance
25,environment,NaN,animal welfare,animal welfare,False,group activist dressed banana costume protested outside edeka supermarket hafentor hamburg hamburg mitte hamburg draw attention use mancozeb pesticide cultivation banana ecuador eu banned mancozeb year denounced serious health risk human right violation worker plantation ecuador exposed
26,labor rights,NaN,public services,policies & politics,False,call ver di around 150 employee supporter youth employment service essen nordrhein westfalen gathered outside council chamber protest city plan cut nearly 20 180 job youth employment sector
27,labor rights,NaN,policies & politics,labor rights,False,around 100 firefighter ver di member protested hannover call money reintroduction full christmas bonus
28,labor rights,NaN,public services,policies & politics,False,300 500 people including cgt affiliate yellow vest 2 pcf national deputy udi mp rn mp local mayor gathered trith saint leger express support 350 valdunes striking employee
29,policies & politics,culture,public services,policies & politics,False,dozen people gathered front city hall paris protested resignation deputy head culture
30,environment,NaN,public services,public services,False,50 people protested puttlingen preservation old railroad embankment
31,public services,NaN,public services,policies & politics,True,least 25 local blocked exit m0 highway budakalasz protest authority plan expand highway would disturb neighborhood
32,policies & politics,NaN,policies & politics,labor rights,True,around 65 yellow vest gathered two location clermont ferrand commemorate movement third year anniversary denounced decreasing purchasing power france
33,immigration,NaN,palestine-israel conflict,immigration,False,people demonstrated malmo skane planned deportation swedish born child pakistan
34,immigration,NaN,housing,housing,False,60 people protested bremen immediate closure refugee accommodation
35,unjust law enforcement,NaN,unjust law enforcement,policies & politics,True,around 80 people gathered koln protest police violence several protester detained previous protest
36,policies & politics,NaN,education,education,False,2024 reported around 600 student wedemark mellendorf grammar school staged rally mellendorf niedersachsen protest defense tolerance diversity protest organized following report secret meeting afd member far right activist potsdam november 2023 remigration plan discussed
37,policies & politics,NaN,policies & politics,animal welfare,True,group activist including sahrawi community gathered front siemens gamesa company zamudio basque country protest plundering resource western sahara carried slogan western sahara sale
38,environment,NaN,policies & politics,policies & politics,False,resident novi beograd activist marched belgrade novi beograd voicing dissatisfaction local government plan build skyscraper within green area part city
39,public services,NaN,policies & politics,policies & politics,False,local resident hispanidad la floresta neighborhood protested zaragoza demanding solution prolongation hayedo street complained blockage project due disagreement public institution
40,policies & politics,NaN,climate,environment,False,around 1 300 people protested wismar demand energy cap amid rising price current energy policy
41,climate,environment,policies & politics,policies & politics,False,1 000 3 000 activist including extinction rebellion village stay friday future activist protested garzweiler open pit mine destruction village surrounding pit mine protester staged protest group protester climbed excavator police private security force energy company rwe ended blockade using force detained eight activist
42,labor rights,policies & politics,labor rights,animal welfare,True,hairdresser protested aranda del duero burgos castilla leon calling government reduce vat rate 21 10 applied labour sector
43,labor rights,NaN,policies & politics,policies & politics,False,agent cadiz local police union csif protested cadiz andalucia break negotiation agreement
44,policies & politics,NaN,public services,public services,False,people including representative left party gathered protest hafencity front hvv headquarters brooktorkai hamburg hamburg opposing recent ban begging hamburg metro city train station
45,labor rights,NaN,immigration,labor rights,False,ugt cig ccoo union delegate protested ferrol coruna demanding readmission 23 worker candido hermida company
46,labor rights,NaN,public services,public services,False,call dgb people including mlpd affiliate gathered cottbus brandenburg protest worker right occasion international worker day
47,ukraine-russia war,NaN,policies & politics,policies & politics,False,15 people peacefully protested neuer markt rostock war europe
48,policies & politics,NaN,pandemic,pandemic,False,around 500 people demonstrated bourg en bresse national security bill condemned violation freedom information protester right medium right well implementation global surveillance citizen
49,policies & politics,NaN,climate,policies & politics,False,around 30 activist pvda ptb staged protest place saint lambert liege denounce current energy price crisis belgium
50,public services,education,policies & politics,health care,False,200 parent child gathered front town hall gerlingen baden wurttemberg council meeting protest rising daycare fee citing unaffordable increase
51,climate,NaN,public services,public services,False,68 across 4 event stop oil protester held slow march blocked traffic london bridge london city london denounce government lack action climate call government halt new oil gas license protester also blocked three bridge time london
52,policies & politics,NaN,unjust law enforcement,education,False,hundred people among student repubblika president gathered casina mafia capaci palermo sicilia commemorate giovanni falcone magistrate killed mafia demonstrate organized crime
53,environment,NaN,culture,environment,False,call surfrider rame pour ta planete surfer gathered bayonne nouvelle aquitaine protest construction metal tower surfing referee 2024 paris olympics teahupoo french polynesia deemed damaging coral
54,immigration,NaN,policies & politics,policies & politics,False,around 30 moroccan protested ibiza balearic island demanding reopening maritime land border
55,labor rights,NaN,public services,public services,False,employee company provides customer service milano linate airport staged protest facility located segrate milano lombardia protester displayed banner air company alitalia decision reduce customer service provider activity airport putting risk many job
56,labor rights,NaN,unjust law enforcement,unjust law enforcement,False,police officer demonstrated front police station beziers call sgp union denounced riot police station champigny sur marne day denounced violence threat experience
57,labor rights,NaN,policies & politics,policies & politics,False,hundred interim civil servant staged protest caravan madrid complain public institution overuse temporary contract protest called slogan fijeza ya fixity
58,policies & politics,discrimination,blm,education,True,unknown number people protested front belgian embassy den haag zuid holland judicial ruling reuzegom case involved death black student hazing ritual organized white student leuven belgium protester found punishment suspect light among protester representative political party bij1 haagse stadspartij action group belgie kan het zwart manifest protester also stressed racist element student death ruling case
59,climate,NaN,policies & politics,policies & politics,False,friday future supporter protested oranienburg climate action
60,labor rights,NaN,animal welfare,labor rights,False,call cgil cisl uil 150 200 people staged protest valentini street front confindustria toscana nord headquarters prato toscana cancellation confindustria territorial agreement would deteriorate worker condition
61,environment,NaN,policies & politics,environment,False,large number citizen organized informal group let stop unlawful change spatial plan mostar zaustavimo nezakonite izmene prostornog plana u mostaru held protest mostar settlement miljkovici construction solar plant hill house settlement miljkovici kozice
62,policies & politics,NaN,ukraine-russia war,environment,False,people including representative christian group protested buchel nuclear weapon storage nuclear weapon u military base buchel
63,labor rights,NaN,policies & politics,policies & politics,False,nearly 50 homeless socially disadvantaged people well shelter volunteer demonstrated firing shelter department head esbjerg
64,labor rights,policies & politics,women rights,animal welfare,False,activist amnesty international marched tromso mark labour day raise awareness human right violation preparation 2022 qatar world cup
65,environment,NaN,environment,public services,True,around 400 citizen called duranguesado air quality platform marched durango iurreta bizkaia protest low air quality
66,environment,NaN,public services,environment,False,people gathered esino river near ancona protest excessive use hydroelectric said damaging river demand better maintenance italian river general
67,climate,NaN,education,education,False,150 people including fff student protested front siemens office munchen company decision maintain participation coal project adani australia
68,labor rights,NaN,public services,policies & politics,False,street vendor protested front city hall crotone crotone calabria change location monthly market
69,culture,labor rights,public services,labor rights,False,2020 people theater worker protested oberhausen closure musical theater
70,policies & politics,NaN,policies & politics,pandemic,True,around 70 member npd protested dresden antifa ban people gathered counterprotest
71,labor rights,NaN,labor rights,policies & politics,True,hundred staff newry mourne district council went strike picketed pay condition outside council office newry represented union unite union gmb nipsa siptu
72,labor rights,NaN,policies & politics,labor rights,False,job placement advisor dubbed navigator gathered front ministry labor social policy rome city center rom lazio demand guarantee category future
73,culture,environment,policies & politics,environment,False,people protested outside redruth town council office redruth controversial planning application build property radnor due proximity wheal peevor mine world heritage site
74,health care,NaN,pandemic,culture,False,around 100 people marched torre annunziata campania pompei campania archaeological site protest closed emergency room boscotrecase
75,education,NaN,policies & politics,education,False,around 40 student dortmund bochum paderborn bielefeld gathered front regional church office bielefeld nordrhein westfalen protest planned budget cut evangelical church westphalia urge church reconsider decision reduce funding student congregation one million euro 500 000 euro amidst broader budget cut 8 8 million euro
76,policies & politics,NaN,policies & politics,discrimination,True,around 250 people gathered mannheim commemorate end second world war liberation nazi regime protester called 8 may delcared national holiday protest organized vvn bda attended antifa
77,policies & politics,NaN,policies & politics,public services,True,30 aliud activist took part march centre torino remember foibe massacre demand better acknowledgement historical sequence public authority sign protest 50 activist left wing autonomous social centre simultaneously staged bike ride city calling kicking fascist district presence police force reportedly prevented form interaction violence
78,policies & politics,NaN,lgbtq,pandemic,False,motto end violence safe coexistence around 50 people gathered schwerte nordrhein westfalen response knife attack occurred week earlier participant expressed concern rising violence protested need greater safety
79,policies & politics,NaN,policies & politics,animal welfare,True,afternoon call jniv veteran trouble marched city center gathered whitehall london westminster england protest labour plan repeal legacy act act granted immunity inquest civil action british military personnel served northern ireland conflict
80,policies & politics,NaN,public services,pandemic,False,group motorcyclist protested front riigikogu tallinn estonia calling new car tax
81,health care,public services,health care,policies & politics,True,people staged protest outside guildhall kingston upon hull england calling council reinstate funding endike community care supported people dementia time reporting
82,labor rights,NaN,public services,public services,False,around 300 worker airbus aeronautical industry protested cadiz demanding aviation sector continuity province plant possible closure
83,policies & politics,NaN,ukraine-russia war,policies & politics,False,protest held war veteran outside foreign affair ministry moldova protester demanded resignation foreign minister statement 1992 war
84,environment,NaN,policies & politics,environment,False,group local resident gathered galleguillos salamanca protest establishment composting plant close town
85,unjust law enforcement,NaN,health care,health care,False,tav movement activist gathered pisa pisa toscana protest police violence event organized response hospitalization fellow activist hit eye smoke grenade clash police clearing area susa valley build transport hub turin lyon high speed railway
86,public services,NaN,policies & politics,public services,False,several hundred citizen gathered kragujevac condemning recent event 13 year old girl lost life due reckless driving lack local government mechanism prevent occurrence

In [10]:
# Per-event labels: manual (truth) + any alt golds, our model, students, whether the
# model's label is accepted under ACCEPTANCE_GROUPS, and clean_notes (by event id).
cols = {'manual_label': 'manual', 'manual_label_alt': 'alt', 'predicted_class_model': 'our model',
        'predicted_class_students': 'students', 'model_accept': 'accepted', 'clean_notes': 'text'}

def table(df):
    return (df.merge(eval_df[['event_id_cnty', 'clean_notes']], on='event_id_cnty', how='left')
              [list(cols)].rename(columns=cols))


with pd.option_context('display.max_rows', None, 'display.max_colwidth', None):
    display(table(rand))

,manual,alt,our model,students,accepted,text
0,labor rights,NaN,labor rights,labor rights,True,morning call fnv around 100 striking iff worker staged picket outside factory gate tilburg noord brabant demand 7 wage increase senior scheme better condition following initial 24 hour strike earlier week
1,policies & politics,NaN,policies & politics,policies & politics,True,people demonstrated paris call bank government drop public debt african country
2,labor rights,NaN,public services,pandemic,False,striking stv journalist represented national union journalist nuj held picket outside scottish parliament edinburgh scotland row pay rise cost living crisis event part national day action
3,labor rights,NaN,climate,farmers,False,hundred unionized employee alro aluminium plant protested slatina complaining high price energy led reduction production capacity demanding permission company negotiate energy delivery directly energy producer
4,climate,NaN,public services,climate,False,extinction rebellion activist gathered outside stock exchange milano municipio 1 staged flash mob protest climate crisis demand finance tackle climate emergency
5,climate,NaN,environment,climate,True,throughout afternoon 11 member last generation gathered konrad adenauer bridge mannheim ludwigshafen mannheim climate protection 5 people stuck road direction mannheim 4 activist side road another action took place feeding lane square q6 q7
6,policies & politics,NaN,public services,housing,False,relative victim member mayor executive unrolled banner balcony town hall palazzo pretorio palermo palermo sicilia demand justice regarding death italian un aid worker found dead apartment san vincente del caguan colombia july 2020
7,policies & politics,NaN,policies & politics,policies & politics,True,three activist gathered protest izola planned purchase local dock military
8,climate,NaN,pandemic,environment,False,around 150 people mostly fff member cycled demonstrated halle saale call climate protection occasion co27 egypt cycled universitatsplatz passage 13 neustadt
9,labor rights,NaN,labor rights,labor rights,True,striking amazon worker represented gmb picketed company fulfillment center coventry dispute pay working condition
10,environment,NaN,pandemic,environment,False,10 member rouvikonas threw flyer premise construction company northern athens protest construction landfill planned corfu
11,discrimination,policies & politics,policies & politics,policies & politics,True,mother child disability protested demanding resignation deputy prime minister valeri simeonov insulting comment
12,policies & politics,NaN,policies & politics,policies & politics,True,motto colorful diverse together extremist parliament around 200 people gathered market square radeberg sachsen protest right wing extremism
13,public services,NaN,public services,public services,True,call ffmc around 600 motorcyclist took street pau nouvelle aquitaine demonstrate introduction compulsory technical inspection two wheel vehicle
14,policies & politics,NaN,policies & politics,policies & politics,True,around 150 people gathered mindelheim bayern protest afd district association bock beer festival
15,labor rights,NaN,labor rights,labor rights,True,justice administration official held protest santa cruz de tenerife santa cruz de tenerife canarias demand salary increase protest summoned csif staj ccoo ugt
16,policies & politics,NaN,policies & politics,lgbtq,True,pegida staged protest dresden sachsen motto foot quergida fascism people staged counter protest several people held sit nearby protest motif specified
17,labor rights,NaN,labor rights,policies & politics,True,employee macedonian information agency protested skopje demanding salary national news agency increased parliament consider request
18,labor rights,farmers,climate,pandemic,False,striking fisher gathered port gallipoli lecce puglia protest increase oil gas price denounce impact category
19,education,NaN,education,education,True,student staged walkout demonstration jyvaskyla keski suomi oppose plan merge school single large campus citing concern overcrowding lack individual support
20,labor rights,NaN,labor rights,public services,True,taxi driver representing app driver courier union gathered outside uber office manchester part 24 hour strike protest poor pay condition unfair dismissal driver demanded rate set 2 gbp per mile part series co ordinated strike member union across several city country attendance representative unite union
21,policies & politics,NaN,policies & politics,policies & politics,True,people including antifa activist participated protest outside italian consulate stuttgart baden wurttemberg demand freedom gabri anti fascist arrested night 21 november 2023 italy charge involved attack fascist budapest february 2023 facing extradition hungary show solidarity imprisoned deceased anti fascist
22,climate,NaN,pandemic,climate,False,friday future activist protested ravensburg climate action
23,immigration,NaN,policies & politics,policies & politics,False,several thousand people protested vienna inner city wien karlsplatz reception refugee right refugee protest organized platform human right attended amongst others granny right
24,public services,NaN,policies & politics,environment,False,resident village glogovo protested teteven claim unacceptable water rationing measure 25 year water supplied one hour per day demand local authority lovech something change
25,policies & politics,unjust law enforcement,unjust law enforcement,labor rights,True,2023 reported 40 anarchist gathered outside ministry health rome city center rom lazio protest detention well known anarchist activist article 41 bi prison regime started hunger strike 20 october 2022
26,policies & politics,public services,public services,education,True,student gathered second consecutive day front faculty economics subotica honor victim novi sad tragedy observed 15 minute moment silence called accountability responsible death
27,policies & politics,NaN,policies & politics,pandemic,True,call reporter without border citizen demonstrated toulouse call liberation french journalist held hostage armed group mali
28,labor rights,NaN,labor rights,labor rights,True,around 30 former employee frank et pignard demonstrated front factory thyez denounced redundancy plan company
29,farmers,NaN,animal welfare,animal welfare,False,20 pig owner continued blockade yambol sliven road protest government decision slaughter pig due swine fever epidemic
30,environment,NaN,policies & politics,environment,False,50 activist resident protested diklo waste disposal site neighborhood
31,labor rights,NaN,public services,labor rights,False,repsol refinery worker held protest coruna galicia death worker unai martinez died accident refinery facility working
32,unjust law enforcement,NaN,unjust law enforcement,unjust law enforcement,True,overnight 30 rioter took street ale hurled projectile molotov cocktail local police station damaging facade police officer responded tear gas rioter also burned container elsewhere town event part national wave riot demonstration denouncing police violence demanding justice wake shooting subsequent death 17 year old nahel police officer nanterre 27 june 2023
33,labor rights,NaN,public services,public services,False,around 100 sam foundry worker affiliated cgt union blocked train station rodez denounce closure factory
34,labor rights,NaN,labor rights,labor rights,True,former adecco amazon worker gathered outside amazon warehouse colleferro rom lazio protest non renewal job contract exploitation temporary work company labor union usb pc representative took part demonstration
35,environment,NaN,policies & politics,policies & politics,False,100 150 people cgt affiliate municipal councilor enora chopard eelv gathered rouen normandie protest lack government action lubrizol factory fire 26 september 2019
36,policies & politics,NaN,policies & politics,public services,True,resident pakrovace near cacak protested delayed payment land seized construction highway area claimed price offered land low
37,climate,NaN,environment,environment,True,people including scientist rebellion member catholic jesuit priest demonstrated munchen karlzplatz climate protection glued hand road
38,policies & politics,NaN,policies & politics,policies & politics,True,hundred citizen cuban community protested madrid centro express support demonstrator protesting cuban regime demanded freedom democracy vox people party supported protest
39,unjust law enforcement,NaN,lgbtq,labor rights,False,around 100 people demonstrated front tribunal meaux denounce death year prisoner hand prison guard call justice
40,culture,NaN,ukraine-russia war,culture,False,croatian capital zagreb 200 people protested announced closure europe cinema oldest active cinema croatia
41,climate,NaN,climate,environment,True,3 climate activist protested greenpeace ship sailing near beatrice wind farm highland offshore coded lybster calling transition oil worker amid national energy transition campaign reported 300 offshore worker facing annual gbp1 600 fee repeat training course
42,labor rights,NaN,public services,climate,False,fisher staged demonstration port bisceglie barletta andria trani puglia protest increase price diesel fuel
43,labor rights,NaN,discrimination,discrimination,False,30 social assistant protested targu mures included government ordinance 19 2024 affect remuneration argue exclusion discriminatory compared similar category included ordinance
44,public services,NaN,public services,public services,True,business owner based main road limassol protested road work area particularly construction road dividing island holding spade driving tractor
45,environment,NaN,animal welfare,animal welfare,False,group activist dressed banana costume protested outside edeka supermarket hafentor hamburg hamburg mitte hamburg draw attention use mancozeb pesticide cultivation banana ecuador eu banned mancozeb year denounced serious health risk human right violation worker plantation ecuador exposed
46,labor rights,NaN,public services,policies & politics,False,call ver di around 150 employee supporter youth employment service essen nordrhein westfalen gathered outside council chamber protest city plan cut nearly 20 180 job youth employment sector
47,labor rights,NaN,policies & politics,labor rights,False,around 100 firefighter ver di member protested hannover call money reintroduction full christmas bonus
48,labor rights,NaN,public services,policies & politics,False,300 500 people including cgt affiliate yellow vest 2 pcf national deputy udi mp rn mp local mayor gathered trith saint leger express support 350 valdunes striking employee
49,labor rights,NaN,labor rights,labor rights,True,call dgb hundred people gathered marktplatz bonn protest worker right occasion international worker day
50,women rights,unjust law enforcement,women rights,unjust law enforcement,True,protester rallied outside courthouse athens central athens shouting slogan demanding conviction accused trial case rape trafficking 12 year old girl kolonos nearing end police announced sue protester one banner accusing authority cover 6 accused found innocent
51,policies & politics,culture,public services,policies & politics,False,dozen people gathered front city hall paris protested resignation deputy head culture
52,environment,NaN,public services,public services,False,50 people protested puttlingen preservation old railroad embankment
53,policies & politics,NaN,policies & politics,policies & politics,True,2021 17 january 19 january least 20 anarchist including male comrade female comrade saekm protested 15 location central wider thessaloniki unfurling banner scattering flier shouting slogan express solidarity dimitris koufodinas convicted hitman defunct group november 17 hunger strike since 8 january transfer rural low security prison higher security prison
54,public services,NaN,public services,policies & politics,True,least 25 local blocked exit m0 highway budakalasz protest authority plan expand highway would disturb neighborhood
55,policies & politics,NaN,policies & politics,labor rights,True,around 65 yellow vest gathered two location clermont ferrand commemorate movement third year anniversary denounced decreasing purchasing power france
56,policies & politics,NaN,policies & politics,policies & politics,True,call democracy network demokratie netzwerk people gathered viersen nordrhein westfalen protest far right ideology event part nationwide protest movement focused defending democracy ahead 2025 federal election
57,education,NaN,education,education,True,around 50 student held protest front jean marie le bris high school douarnenez platform parcoursup reform professional high school lack school personnel event part national cross sector day strike protest called cgt fo sud fsu union well fidl mnl unef high school voice student organization demand salary increase amid inflation defend right strike
58,labor rights,NaN,labor rights,labor rights,True,shellfishers traveled protest caravan ferrol coruna demanding solution difficult labor situation due shortage product
59,policies & politics,NaN,policies & politics,policies & politics,True,around 200 people including member spd mlpd igbce green left fvc demonstrated herten ongoing rally far right political party afd yelled nazi protester far right idea fascism
60,immigration,NaN,palestine-israel conflict,immigration,False,people demonstrated malmo skane planned deportation swedish born child pakistan
61,immigration,NaN,housing,housing,False,60 people protested bremen immediate closure refugee accommodation
62,policies & politics,NaN,policies & politics,policies & politics,True,protester marched pluzine montenegro new religious freedom law serbian orthodox church feel unfairly targeted law
63,unjust law enforcement,NaN,unjust law enforcement,policies & politics,True,around 80 people gathered koln protest police violence several protester detained previous protest
64,policies & politics,NaN,policies & politics,policies & politics,True,around 200 people gathered francavilla fontana brindisi puglia ask justice death young man killed front house circumstance yet clarified mayor francavilla fontana civic list latiano civic list san pietro vernotico independent member municipal administration government took part demonstration libera uds organized demonstration
65,policies & politics,NaN,education,education,False,2024 reported around 600 student wedemark mellendorf grammar school staged rally mellendorf niedersachsen protest defense tolerance diversity protest organized following report secret meeting afd member far right activist potsdam november 2023 remigration plan discussed
66,policies & politics,public services,public services,public services,True,2nd anniversary tempe rail disaster day independent investigation report released blaming human error outdated infrastructure major systemic failure 24 hour general strike protester rallied orestiada slogan oxygen demanding justice accountability
67,policies & politics,NaN,policies & politics,animal welfare,True,group activist including sahrawi community gathered front siemens gamesa company zamudio basque country protest plundering resource western sahara carried slogan western sahara sale
68,policies & politics,NaN,policies & politics,policies & politics,True,activist including kod member gathered rally myslenice protesting new law medium ownership perceive harmful pressure government independent medium
69,environment,NaN,policies & politics,policies & politics,False,resident novi beograd activist marched belgrade novi beograd voicing dissatisfaction local government plan build skyscraper within green area part city
70,public services,NaN,policies & politics,policies & politics,False,local resident hispanidad la floresta neighborhood protested zaragoza demanding solution prolongation hayedo street complained blockage project due disagreement public institution
71,policies & politics,NaN,climate,environment,False,around 1 300 people protested wismar demand energy cap amid rising price current energy policy
72,policies & politics,NaN,policies & politics,policies & politics,True,around hundred citizen gathered zadar voice opposition handing building zadar county zadar archdiocese protester stated church want community real estate instead community believer
73,labor rights,NaN,labor rights,labor rights,True,around 150 200 people including one spd member protested oberhausen occasion may day labor day protest organized ib exact reason protest reported
74,policies & politics,NaN,policies & politics,policies & politics,True,several thousand activist gathered rally zenica protesting inflation high tax related economic cost
75,public services,NaN,public services,housing,True,100 resident including business owner held protest redondela galicia denounce removal parking space due street redevelopment impacting commerce resident life
76,environment,NaN,environment,environment,True,70 80 citizen gathered palma de mallorca protest establiments quarry reopening
77,education,health care,health care,health care,True,around hundred trainee doctor gathered front region headquarters torino protest access medical specialisation main complaint current system let graduated student specialise
78,labor rights,NaN,labor rights,labor rights,True,police officer protested banja luka bosnia herzegovina demanding better retirement condition
79,policies & politics,NaN,policies & politics,policies & politics,True,pending ruling british high court regarding extradition wikileaks founder julian assange people gathered near duomo milano municipio 1 lombardia stage demonstration part international event solidarity assange freedom press protester also placed temporary monument dedicated assange near duomo
80,climate,environment,policies & politics,policies & politics,False,1 000 3 000 activist including extinction rebellion village stay friday future activist protested garzweiler open pit mine destruction village surrounding pit mine protester staged protest group protester climbed excavator police private security force energy company rwe ended blockade using force detained eight activist
81,unjust law enforcement,NaN,unjust law enforcement,unjust law enforcement,True,around 100 people protested stade afghan refugee shot dead police officer police operation one year ago demanding investigation death
82,labor rights,policies & politics,labor rights,animal welfare,True,hairdresser protested aranda del duero burgos castilla leon calling government reduce vat rate 21 10 applied labour sector
83,policies & politics,NaN,policies & politics,policies & politics,True,approximately 30 people protested outside sibiu tribunal condemning government attack judiciary
84,labor rights,NaN,policies & politics,policies & politics,False,agent cadiz local police union csif protested cadiz andalucia break negotiation agreement
85,policies & politics,NaN,policies & politics,policies & politics,True,protester piatra neamt rallied corruption policy romanian government
86,policies & politics,labor rights,policies & politics,policies & politics,True,ccoo ugt trade union member protested zaragoza aragon support cgil italian union neo fascist group attacked headquarters 9 october
87,labor rights,policies & politics,labor rights,labor rights,True,worker demonstrated oulu pohjois pohjanmaa support ongoing strike government proposed labor market reform benefit cut
88,policies & politics,NaN,public services,public services,False,people including representative left party gathered protest hafencity front hvv headquarters brooktorkai hamburg hamburg opposing recent ban begging hamburg metro city train station
89,education,NaN,education,education,True,around 40 parent protested perigueux budget cut concerning resource allocated start 2021 school year could cause closure class denounced disparity urban rural high school