# Model vs students on hand-labeled unseen data

The two prediction sources (`filtered_events_class_with_predicted.csv` and
`..._students.csv`) disagree on tens of thousands of events whose trigger-word
ground truth is `unknown`. For those there is no label to score against, so we
**hand-labeled a sample**.

`manual_labeled_unknown.csv` is 70 such events — all `unknown` to the trigger words
and where the model and students models predict *different* classes — each assigned a
manual label from the model's allowed 20-class taxonomy, based only on the event
`notes`. This notebook scores both models against those manual labels.

Because every row was picked specifically where the two models disagree, at most one
of them can be right on any given row — so these accuracies are a worst-case probe of
behaviour on ambiguous `unknown` events, not the models' overall accuracy.

In [1]:
import pandas as pd
import plotly.express as px

df = pd.read_csv('manual_labeled_unknown.csv')
df['model_correct'] = df['predicted_class_model'] == df['manual_label']
df['students_correct'] = df['predicted_class_students'] == df['manual_label']
print(f'{len(df)} hand-labeled events')
df.head()

70 hand-labeled events

,event_id_cnty,manual_label,predicted_class_model,predicted_class_students,notes,model_correct,students_correct
0,CYP517,public services,labor rights,policies & politics,"On 28 September 2020, about 50 members of the ...",False,False
1,ITA23103,lgbtq,policies & politics,lgbtq,"On 18 May 2024, a large group of people took p...",False,True
2,ITA7407,labor rights,public services,policies & politics,"On 26 March 2021, food delivery riders rode on...",False,False
3,FRA19654,labor rights,lgbtq,policies & politics,"On 19 October 2022, employees of the Sidel com...",False,False
4,GBR8516,public services,policies & politics,culture,"On 28 April 2025, at the call of Unison and Un...",False,False

## Accuracy against the manual labels

Share of the 70 events where each model's predicted class matches the hand-assigned
label. `neither` is the share where both models were wrong (recall they always
disagree, so they can never both be right).

In [2]:
model_acc = df['model_correct'].mean()
students_acc = df['students_correct'].mean()
neither = (~df['model_correct'] & ~df['students_correct']).mean()

summary = pd.DataFrame({
    'outcome': ['Model correct', 'Students correct', 'Neither correct'],
    'share': [model_acc, students_acc, neither],
    'count': [df['model_correct'].sum(), df['students_correct'].sum(),
              (~df['model_correct'] & ~df['students_correct']).sum()],
})
display(summary)

fig = px.bar(summary, x='outcome', y='share', color='outcome', text=summary['share'].round(3),
             labels={'outcome': '', 'share': 'Share of events'})
fig.update_layout(title={'text': 'Agreement with manual labels (disagreeing unknown events)', 'x': 0.5},
                  plot_bgcolor='white', width=700, height=450,
                  yaxis={'range': [0, 1.05]}, showlegend=False)
fig.show()

            outcome     share  count
0     Model correct  0.100000      7
1  Students correct  0.442857     31
2   Neither correct  0.457143     32

## Where each model wins, by manual label

For each true (manual) class, how many of its events the model got right versus the
students model. Bars to the right of zero are events the students model won; to the
left are events the model won.

In [3]:
by_class = df.groupby('manual_label').agg(
    n=('manual_label', 'size'),
    model=('model_correct', 'sum'),
    students=('students_correct', 'sum'),
).sort_values('n', ascending=False).reset_index()
display(by_class)

melted = by_class.melt(id_vars=['manual_label', 'n'], value_vars=['model', 'students'],
                       var_name='source', value_name='correct')
fig = px.bar(melted, x='correct', y='manual_label', color='source', orientation='h',
             barmode='group', labels={'correct': 'Events correct', 'manual_label': 'Manual label',
                                      'source': ''})
fig.update_layout(title={'text': 'Correct predictions per manual label', 'x': 0.5},
                  plot_bgcolor='white', width=850, height=550,
                  yaxis={'categoryorder': 'total ascending'})
fig.show()

              manual_label   n  model  students
0             labor rights  19      4         8
1      policies & politics  18      3        12
2          public services   6      0         1
3             women rights   5      0         3
4                  climate   5      0         2
5   unjust law enforcement   4      0         2
6              health care   3      0         1
7                  housing   3      0         1
8              environment   3      0         0
9           discrimination   1      0         0
10                 culture   1      0         0
11          animal welfare   1      0         0
12                   lgbtq   1      0         1

## Per-event detail

Every event with the manual label, both predictions, and who (if anyone) was right.

In [4]:
def winner(r):
    if r['model_correct']:
        return 'model'
    if r['students_correct']:
        return 'students'
    return 'neither'

detail = df.copy()
detail['correct'] = detail.apply(winner, axis=1)
detail = detail[['event_id_cnty', 'manual_label', 'predicted_class_model',
                 'predicted_class_students', 'correct', 'notes']]
with pd.option_context('display.max_colwidth', 90, 'display.max_rows', 100):
    display(detail)

,event_id_cnty,manual_label,predicted_class_model,predicted_class_students,correct,notes
0,CYP517,public services,labor rights,policies & politics,neither,"On 28 September 2020, about 50 members of the Turkish Cypriot electricity union EL-SEN..."
1,ITA23103,lgbtq,policies & politics,lgbtq,students,"On 18 May 2024, a large group of people took part in the pride parade in Parma (Emilia..."
2,ITA7407,labor rights,public services,policies & politics,neither,"On 26 March 2021, food delivery riders rode on their bikes through the streets and lat..."
3,FRA19654,labor rights,lgbtq,policies & politics,neither,"On 19 October 2022, employees of the Sidel company gathered for a picket, as a part of..."
4,GBR8516,public services,policies & politics,culture,neither,"On 28 April 2025, at the call of Unison and Unite, campaigners gathered outside the Co..."
5,FRA27350,labor rights,environment,lgbtq,neither,"On 1 September 2023, people, including Valdunes employees and CGT affiliates, demonstr..."
6,ITA17129,labor rights,animal welfare,education,neither,"On 28 September 2022, nine former Keller workers climbed onto the rooftop of the Anas ..."
7,ESP2375,unjust law enforcement,labor rights,women rights,neither,"On 27 October 2020, citizens from Nigeria, predominantly women, gathered in Villabona ..."
8,AUT609,labor rights,public services,education,neither,"On 1 May 2021, between 400 to 600 people protested in Salzburg on the occasion of May ..."
9,LVA257,public services,policies & politics,public services,students,"On 30 April 2024, residents of Roja with about 250 cars drove through the Roja-Valdema..."
10,NLD3143,climate,public services,environment,neither,"On 1 June 2024, an unknown number of XR activists organized a protest action in Rotter..."
11,BGR1545,policies & politics,labor rights,policies & politics,students,"On 14 October 2020, relatives of a man who was murdered protested in Vidin demanding p..."
12,ITA24210,women rights,animal welfare,policies & politics,neither,"On 15 October 2024, at the call of CGIL, CISL and UIL, people, including women, staged..."
13,ESP16637,environment,policies & politics,housing,neither,"On 27 March 2024, members of UGT held a protest in front of the City Hall in Granada (..."
14,HRV934,policies & politics,labor rights,policies & politics,students,"On 2 July 2023, citizens and Homeland Movement representatives protested in Varazdin a..."
15,BIH778,policies & politics,labor rights,policies & politics,students,"On 10 January 2022, residents of Tuzla gathered on the main square to protest against ..."
16,FRA21944,policies & politics,lgbtq,policies & politics,students,"On 4 February 2023, between 700 people (according to the police) and 2,500 people (acc..."
17,DEU7243,housing,public services,housing,students,"On 19 June 2021, around 50 people protested in Gottingen at the call of the DGB agains..."
18,MLT6,policies & politics,lgbtq,policies & politics,students,"On 29 January 2020, about 400 people gathered in front of the Parliament building in V..."
19,SWE3096,women rights,unjust law enforcement,women rights,students,"On 1 October 2022, demonstrators, mostly members of the Swedish-Iranian community, gat..."
20,ITA12360,labor rights,public services,labor rights,students,"On 8 November 2021, Saga Coffee workers continued to block the entrance of their compa..."
21,GRC4319,policies & politics,public services,policies & politics,students,"On 14 May 2023, about 2.000 protesters - including citizens of Serres, members of civi..."
22,FRA4028,labor rights,public services,labor rights,students,"On 6 November 2020, delivery employees of Uber, including undocumented employees, demo..."
23,FRA27036,unjust law enforcement,lgbtq,unjust law enforcement,students,"On 1 July 2023, overnight, rioters took to the streets and set on fire garbage contain..."
24,ITA10339,environment,lgbtq,public services,neither,"On 24 July 2021, during the night, around 150 No TAV Movement activists, among them me..."
25,SWE6393,women rights,lgbtq,policies & politics,neither,"On 21 November 2024, people staged a torchlight procession in Finspang, Ostergotland, ..."
26,GBR4877,policies & politics,policies & politics,pandemic,model,"On 30 April 2022, loyalists gathered in Bangor to protest against the Northern Ireland..."
27,SRB4660,unjust law enforcement,labor rights,pandemic,neither,"On 21 March 2025, citizens, PSG, and civil society representatives gathered in front o..."
28,FRA15457,labor rights,animal welfare,labor rights,students,"On 17 February 2022, at the call of the CGT, a dozen social security workers demonstra..."
29,SRB699,policies & politics,lgbtq,policies & politics,students,"On 16 March 2019, in Kragujevac, Serbia, citizens held a '1 of 5 Million' protest agai..."
30,FIN483,environment,culture,farmers,neither,"On 11 November 2021, a protest against mining took place in Savonlinna."
31,ESP9601,culture,lgbtq,policies & politics,neither,"On 20 March 2022, more than 100 residents and members of 'In defense of the Virgen de ..."
32,ITA20210,health care,lgbtq,health care,students,"On 9 June 2023, at the call of the association 'Mental Health Forum', a large group of..."
33,ESP6592,women rights,animal welfare,women rights,students,"On 11 August 2021, around 100 citizens protested in Urnieta, demanding justice for a 2..."
34,MDA1890,policies & politics,policies & politics,health care,model,"On 28 October 2024, people protested near the buildings of the police inspectorate and..."
35,DEU3038,policies & politics,palestine-israel conflict,policies & politics,students,"On 1 September 2020, people protested in Karlsruhe under the motto 'Never Again War! I..."
36,IRL1405,climate,labor rights,climate,students,"On 25 May 2024, climate activists from Mothers' Rebellion staged a sit-in protest at t..."
37,HRV1015,policies & politics,labor rights,policies & politics,students,"On 28 February 2024, citizens protested in Split following the recent murder case of a..."
38,MKD965,discrimination,animal welfare,policies & politics,neither,"On 7 June 2023, citizens with disabilities protested in Skopje demanding improved prot..."
39,DEU5580,climate,animal welfare,environment,neither,"On 19 March 2021, around 100 to 300 Fridays for Future activists protested in Wurzburg..."
40,ITA12921,public services,environment,policies & politics,neither,"On 27 November 2021, people gathered in Verona to demand the reopening of the Golosine..."
41,ITA14577,public services,labor rights,policies & politics,neither,"On 19 February 2022, people gathered in Montale Square in Torino to protest against th..."
42,DEU6818,housing,environment,policies & politics,neither,"Around 19 May 2021 (as reported), activists squatted an empty building in Chemnitz to ..."
43,DEU8143,labor rights,environment,labor rights,students,"On 20 September 2021, around 200 people, including employees of Ontex and SPD members,..."
44,ESP10596,labor rights,labor rights,policies & politics,model,"On 10 June 2022, hundreds of Celsa workers mobilized in Santander (Cantabria) in front..."
45,GRC1038,health care,public services,policies & politics,neither,"On 18 October 2019, four members of Rouvikonas splashed red paint at the entrance and ..."
46,GRC1284,unjust law enforcement,policies & politics,unjust law enforcement,students,"On 7 December 2019, friends and family members of demonstrators, who were arrested on ..."
47,ITA3806,labor rights,public services,pandemic,neither,"On 1 October 2020, around 38 part-time employees of a contracted company that provides..."
48,DEU3767,policies & politics,unjust law enforcement,ukraine-russia war,neither,"On 17 October 2020, Azerbaijani and Turkish protesters gathered near Turkish Embassy i..."
49,FRA21264,housing,lgbtq,policies & politics,neither,"On 21 January 2023, around 200 people, including the local mayor (independent), member..."
50,ESP17646,policies & politics,lgbtq,environment,neither,"On 5 July 2024, around 300 people held a protest in Caldes de Malavella (Cataluna) aga..."
51,FRA33054,policies & politics,lgbtq,policies & politics,students,"On 19 April 2024, around 500 people gathered for a silent march in Romans-sur-Isere (A..."
52,SRB1117,public services,environment,policies & politics,neither,"On 9 July 2019, citizens of Zrenjanin, Serbia, protested over the lack of drinkable wa..."
53,ESP13263,animal welfare,pandemic,farmers,neither,"On 23 April 2023, hundreds of people held a protest in A Coruna (Galicia) to oppose a ..."
54,GBR378,climate,animal welfare,public services,neither,"On 25 February 2020, dozens of Extinction Rebellion activists gathered outside of Exet..."
55,FRA27508,labor rights,labor rights,policies & politics,model,"Around 31 August 2023, at the call of SGLCE-CGT, SNJ-CGT, and BF-UFICT-CGT, workers fr..."
56,DEU3448,climate,animal welfare,climate,students,"On 25 September 2020, Fridays for Future activists protested in Kassel for more climat..."
57,ESP8226,labor rights,labor rights,public services,model,"On 12 January 2022, taxi drivers protested in Valencia, demanding to reduce their work..."
58,MLT170,policies & politics,public services,policies & politics,students,"Around 13 June 2022 (as reported), Residenti Beltin (Beltin Residents) group activists..."
59,FRA889,policies & politics,public services,policies & politics,students,"On 31 January 2020, in the evening, several hundreds of persons gathered in Le Havre. ..."
60,NLD1282,labor rights,environment,labor rights,students,"Around 18 October 2021 (as reported), an unknown number of judicial interpreters stage..."
61,HRV122,health care,public services,policies & politics,neither,"On 21 August 2018, 2018 in Zapresici, Croatia several hundred citizens organized a pro..."
62,ITA9733,labor rights,lgbtq,labor rights,students,"On 22 June 2021, in the evening, Panorama retail workers and trade unionists gathered,..."
63,ESP11418,labor rights,culture,labor rights,students,"On 26 September 2022, hoteliers from the Honduran and adjacent areas held a protest in..."
64,BGR2706,labor rights,labor rights,public services,model,"On 24 October 2022, taxi drivers protested in Sofia demanding more protections for the..."
65,ITA3088,policies & politics,public services,animal welfare,neither,"On 27 July 2020, nearly a dozen people gathered in the Rossellino area of Potenza to p..."
66,FRA32253,labor rights,environment,labor rights,students,"On 2 April 2024, at the call of CGT, striking STEF employees gathered for a picket lin..."
67,DEU1353,women rights,lgbtq,women rights,students,"On 1 May 2020, around 50 people gathered for a 'women strike' in Jena."
68,ITA24091,policies & politics,policies & politics,housing,model,"On 6 October 2024, residents and shop owners staged a demonstration in the Campo di Ma..."
69,IRL1481,labor rights,animal welfare,pandemic,neither,"On 24 July 2024, 15 striking barristers of the Bar of Ireland picketed outside the cou..."